services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  php:
    build: ./php
    command: tail -f /dev/null
    volumes:
      - ./php:/var/www/html
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: appdb
    ports:
      - 5432:5432
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: